-- Create Streamlit object
CREATE OR REPLACE STREAMLIT GMAIL_ANALYTICS.CORE.GMAIL_ANALYTICS_DASHBOARD
    FROM '@GMAIL_ANALYTICS.CORE.STREAMLIT_STAGE'
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = COMPUTE_WH
    TITLE = 'Gmail Analytics Dashboard';

ALTER STREAMLIT GMAIL_ANALYTICS.CORE.GMAIL_ANALYTICS_DASHBOARD ADD LIVE VERSION FROM LAST;
