CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION GMAIL_API_ACCESS_INTEGRATION
    ALLOWED_NETWORK_RULES = (GMAIL_ANALYTICS.CORE.GMAIL_API_NETWORK_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (GMAIL_ANALYTICS.CORE.GMAIL_OAUTH_SECRET)
    ENABLED = TRUE