-- =============================================================================
-- Step 3: 7 base analytics views
-- =============================================================================

CREATE OR REPLACE VIEW GMAIL_ANALYTICS.ANALYTICS.VW_EMAIL_ACTIVITY_DAILY AS
SELECT
    DATE_TRUNC('day', m.SENT_AT)::DATE AS ACTIVITY_DATE,
    COUNT(*) AS TOTAL_MESSAGES,
    COUNT(CASE WHEN m.IS_SENT THEN 1 END) AS SENT_COUNT,
    COUNT(*) - COUNT(CASE WHEN m.IS_SENT THEN 1 END) AS RECEIVED_COUNT,
    COUNT(CASE WHEN m.IS_READ THEN 1 END) AS READ_COUNT,
    COUNT(CASE WHEN NOT m.IS_READ THEN 1 END) AS UNREAD_COUNT,
    COUNT(CASE WHEN m.IS_STARRED THEN 1 END) AS STARRED_COUNT,
    COUNT(CASE WHEN m.HAS_ATTACHMENTS THEN 1 END) AS WITH_ATTACHMENTS,
    COUNT(CASE WHEN m.IS_SUSPICIOUS THEN 1 END) AS SUSPICIOUS_COUNT,
    COUNT(DISTINCT m.THREAD_ID) AS ACTIVE_THREADS,
    COUNT(DISTINCT m.SENDER_CONTACT_ID) AS UNIQUE_SENDERS,
    m.CATEGORY,
    DAYNAME(m.SENT_AT) AS DAY_OF_WEEK,
    HOUR(m.SENT_AT) AS PEAK_HOUR
FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES m
GROUP BY ACTIVITY_DATE, m.CATEGORY, DAY_OF_WEEK, PEAK_HOUR;

CREATE OR REPLACE VIEW GMAIL_ANALYTICS.ANALYTICS.VW_THREAD_SUMMARY AS
SELECT
    t.THREAD_ID, t.SUBJECT, t.CATEGORY, t.MESSAGE_COUNT,
    t.STARTED_AT, t.LAST_MESSAGE_AT,
    DATEDIFF('minute', t.STARTED_AT, t.LAST_MESSAGE_AT) AS THREAD_DURATION_MINUTES,
    COUNT(DISTINCT m.SENDER_CONTACT_ID) AS PARTICIPANT_COUNT,
    COUNT(CASE WHEN m.HAS_ATTACHMENTS THEN 1 END) AS ATTACHMENT_COUNT,
    COUNT(CASE WHEN NOT m.IS_READ THEN 1 END) AS UNREAD_IN_THREAD,
    COUNT(CASE WHEN m.IS_SUSPICIOUS THEN 1 END) AS SUSPICIOUS_IN_THREAD,
    MAX(m.IMPORTANCE) AS MAX_IMPORTANCE,
    LISTAGG(DISTINCT c.DISPLAY_NAME, ', ') WITHIN GROUP (ORDER BY c.DISPLAY_NAME) AS PARTICIPANTS
FROM GMAIL_ANALYTICS.CORE.EMAIL_THREADS t
JOIN GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES m ON t.THREAD_ID = m.THREAD_ID
JOIN GMAIL_ANALYTICS.CORE.EMAIL_CONTACTS c ON m.SENDER_CONTACT_ID = c.CONTACT_ID
GROUP BY t.THREAD_ID, t.SUBJECT, t.CATEGORY, t.MESSAGE_COUNT, t.STARTED_AT, t.LAST_MESSAGE_AT;

CREATE OR REPLACE VIEW GMAIL_ANALYTICS.ANALYTICS.VW_CONTACT_ENGAGEMENT AS
SELECT
    c.CONTACT_ID, c.EMAIL, c.DISPLAY_NAME, c.DOMAIN, c.CONTACT_TYPE, c.IS_INTERNAL,
    COUNT(m.MESSAGE_ID) AS MESSAGES_SENT,
    COUNT(CASE WHEN m.IS_READ THEN 1 END) AS MESSAGES_READ,
    COUNT(CASE WHEN m.HAS_ATTACHMENTS THEN 1 END) AS MESSAGES_WITH_ATTACHMENTS,
    COUNT(DISTINCT m.THREAD_ID) AS THREADS_PARTICIPATED,
    MIN(m.SENT_AT) AS FIRST_MESSAGE_AT,
    MAX(m.SENT_AT) AS LAST_MESSAGE_AT,
    DATEDIFF('day', MIN(m.SENT_AT), MAX(m.SENT_AT)) AS ACTIVE_SPAN_DAYS,
    AVG(m.SPAM_SCORE) AS AVG_SPAM_SCORE,
    COUNT(CASE WHEN m.IS_SUSPICIOUS THEN 1 END) AS SUSPICIOUS_MESSAGES
FROM GMAIL_ANALYTICS.CORE.EMAIL_CONTACTS c
LEFT JOIN GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES m ON c.CONTACT_ID = m.SENDER_CONTACT_ID
GROUP BY c.CONTACT_ID, c.EMAIL, c.DISPLAY_NAME, c.DOMAIN, c.CONTACT_TYPE, c.IS_INTERNAL;

CREATE OR REPLACE VIEW GMAIL_ANALYTICS.ANALYTICS.VW_LABEL_DISTRIBUTION AS
SELECT
    l.LABEL_ID, l.LABEL_NAME, l.LABEL_TYPE, l.COLOR,
    COUNT(DISTINCT lm.MESSAGE_ID) AS MESSAGE_COUNT,
    COUNT(DISTINCT m.THREAD_ID) AS THREAD_COUNT,
    MIN(lm.APPLIED_AT) AS FIRST_APPLIED,
    MAX(lm.APPLIED_AT) AS LAST_APPLIED,
    ROUND(COUNT(DISTINCT lm.MESSAGE_ID) * 100.0 /
        NULLIF((SELECT COUNT(*) FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES), 0), 2) AS PCT_OF_ALL_MESSAGES
FROM GMAIL_ANALYTICS.CORE.EMAIL_LABELS l
LEFT JOIN GMAIL_ANALYTICS.CORE.EMAIL_MESSAGE_LABEL_MAP lm ON l.LABEL_ID = lm.LABEL_ID
LEFT JOIN GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES m ON lm.MESSAGE_ID = m.MESSAGE_ID
GROUP BY l.LABEL_ID, l.LABEL_NAME, l.LABEL_TYPE, l.COLOR;

CREATE OR REPLACE VIEW GMAIL_ANALYTICS.ANALYTICS.VW_SUSPICIOUS_EMAIL_ANALYSIS AS
SELECT
    m.MESSAGE_ID, m.SUBJECT, m.SNIPPET, m.SENT_AT, m.SPAM_SCORE, m.CATEGORY, m.IS_SPAM,
    c.EMAIL AS SENDER_EMAIL, c.DISPLAY_NAME AS SENDER_NAME, c.DOMAIN AS SENDER_DOMAIN,
    c.CONTACT_TYPE,
    TRY_PARSE_JSON(m.PHISHING_INDICATORS) AS PHISHING_FLAGS,
    TRY_PARSE_JSON(m.PHISHING_INDICATORS):urgency::BOOLEAN AS HAS_URGENCY,
    TRY_PARSE_JSON(m.PHISHING_INDICATORS):suspicious_links::BOOLEAN AS HAS_SUSPICIOUS_LINKS,
    TRY_PARSE_JSON(m.PHISHING_INDICATORS):impersonation::BOOLEAN AS HAS_IMPERSONATION,
    TRY_PARSE_JSON(m.PHISHING_INDICATORS):request_credentials::BOOLEAN AS REQUESTS_CREDENTIALS,
    t.SUBJECT AS THREAD_SUBJECT, t.MESSAGE_COUNT AS THREAD_MESSAGE_COUNT
FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES m
JOIN GMAIL_ANALYTICS.CORE.EMAIL_CONTACTS c ON m.SENDER_CONTACT_ID = c.CONTACT_ID
JOIN GMAIL_ANALYTICS.CORE.EMAIL_THREADS t ON m.THREAD_ID = t.THREAD_ID
WHERE m.IS_SUSPICIOUS = TRUE OR m.SPAM_SCORE > 0.5;

CREATE OR REPLACE VIEW GMAIL_ANALYTICS.ANALYTICS.VW_ATTACHMENT_ANALYTICS AS
SELECT
    a.ATTACHMENT_ID, a.FILENAME, a.CONTENT_TYPE, a.SIZE_BYTES,
    ROUND(a.SIZE_BYTES / 1024.0 / 1024.0, 2) AS SIZE_MB,
    a.IS_INLINE, m.MESSAGE_ID, m.SUBJECT, m.CATEGORY, m.SENT_AT,
    c.DISPLAY_NAME AS SENDER_NAME, c.DOMAIN AS SENDER_DOMAIN,
    SPLIT_PART(a.FILENAME, '.', -1) AS FILE_EXTENSION,
    CASE
        WHEN a.CONTENT_TYPE LIKE 'image/%' THEN 'Image'
        WHEN a.CONTENT_TYPE LIKE 'application/pdf' THEN 'PDF'
        WHEN a.CONTENT_TYPE LIKE '%spreadsheet%' OR a.CONTENT_TYPE LIKE '%excel%' THEN 'Spreadsheet'
        WHEN a.CONTENT_TYPE LIKE '%presentation%' OR a.CONTENT_TYPE LIKE '%powerpoint%' THEN 'Presentation'
        WHEN a.CONTENT_TYPE LIKE '%document%' OR a.CONTENT_TYPE LIKE '%word%' THEN 'Document'
        WHEN a.CONTENT_TYPE LIKE 'text/%' THEN 'Text'
        WHEN a.CONTENT_TYPE LIKE '%zip%' THEN 'Archive'
        ELSE 'Other'
    END AS FILE_TYPE_GROUP
FROM GMAIL_ANALYTICS.CORE.EMAIL_ATTACHMENTS a
JOIN GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES m ON a.MESSAGE_ID = m.MESSAGE_ID
JOIN GMAIL_ANALYTICS.CORE.EMAIL_CONTACTS c ON m.SENDER_CONTACT_ID = c.CONTACT_ID;

CREATE OR REPLACE VIEW GMAIL_ANALYTICS.ANALYTICS.VW_SNOWFLAKE_ALERTS AS
SELECT
    m.MESSAGE_ID, m.SUBJECT, m.BODY_TEXT, m.SENT_AT, m.IMPORTANCE,
    c.DISPLAY_NAME AS ALERT_SOURCE, c.EMAIL AS ALERT_EMAIL,
    CASE
        WHEN m.SUBJECT LIKE '%credit%' OR m.SUBJECT LIKE '%quota%' THEN 'Credit/Billing'
        WHEN m.SUBJECT LIKE '%Task%failed%' OR m.SUBJECT LIKE '%error%' THEN 'Task Failure'
        WHEN m.SUBJECT LIKE '%Storage%' THEN 'Storage'
        WHEN m.SUBJECT LIKE '%performance%' OR m.SUBJECT LIKE '%Warehouse%' THEN 'Performance'
        WHEN m.SUBJECT LIKE '%login%' OR m.SUBJECT LIKE '%Security%' THEN 'Security'
        WHEN m.SUBJECT LIKE '%Resource monitor%' THEN 'Resource Monitor'
        WHEN m.SUBJECT LIKE '%Pipe%' THEN 'Data Loading'
        ELSE 'Other'
    END AS ALERT_TYPE,
    DATE_TRUNC('week', m.SENT_AT)::DATE AS ALERT_WEEK,
    DATE_TRUNC('month', m.SENT_AT)::DATE AS ALERT_MONTH
FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES m
JOIN GMAIL_ANALYTICS.CORE.EMAIL_CONTACTS c ON m.SENDER_CONTACT_ID = c.CONTACT_ID
WHERE m.SUBJECT LIKE '%[Snowflake]%'
   OR c.EMAIL LIKE '%@snowflakecomputing.com'
   OR c.EMAIL LIKE '%@snowflake.com';