-- =============================================================================
-- Verification queries
-- =============================================================================

SELECT 'EMAIL_CONTACTS' AS TBL, COUNT(*) AS CNT FROM GMAIL_ANALYTICS.CORE.EMAIL_CONTACTS
UNION ALL SELECT 'EMAIL_THREADS', COUNT(*) FROM GMAIL_ANALYTICS.CORE.EMAIL_THREADS
UNION ALL SELECT 'EMAIL_MESSAGES', COUNT(*) FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES
UNION ALL SELECT 'EMAIL_ATTACHMENTS', COUNT(*) FROM GMAIL_ANALYTICS.CORE.EMAIL_ATTACHMENTS
UNION ALL SELECT 'EMAIL_LABELS', COUNT(*) FROM GMAIL_ANALYTICS.CORE.EMAIL_LABELS
UNION ALL SELECT 'EMAIL_MESSAGE_LABEL_MAP', COUNT(*) FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGE_LABEL_MAP;

SELECT CATEGORY, COUNT(*) AS CNT FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES GROUP BY CATEGORY ORDER BY CNT DESC;

SELECT COUNT(*) AS SUSPICIOUS FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES WHERE IS_SUSPICIOUS = TRUE;

SELECT MIN(SENT_AT) AS EARLIEST, MAX(SENT_AT) AS LATEST FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES;

SELECT 'Synthetic' AS SOURCE, COUNT(*) AS MESSAGES FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES WHERE MESSAGE_ID < 10000
UNION ALL SELECT 'Real Gmail', COUNT(*) FROM GMAIL_ANALYTICS.CORE.EMAIL_MESSAGES WHERE MESSAGE_ID >= 10000;